org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.22)
neo_version=21.1.62
neo_version_range=[21.1,)
loader_version_range=[4,)

## Mod Properties
mod_id=oreveins
mod_name=Customizable Ore Veins
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.example.oreveins
mod_authors=You
mod_description=Configurable ore-vein nodes that yield a set total amount of ore before depleting.
